.\" Manpage for git-bump
.TH man 1 "March 2014" "1.0" "git bump man page"
.SH NAME
git bump \- Apply a version-bumped tag to your repo
.SH SYNOPSIS
git bump <environment>
.SH DESCRIPTION
Tag your repo with a new auto-incremented version number, in preparation for deployment.
.SH OPTIONS
.TP
.I <environment>
Name of the environment to bump for, the config for which is kept in .git-deploy
.I
.SH SEE ALSO
git-deploy(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Barney Desmond <barneydesmond@gmail.com>
