.\" Manpage for git-deploy
.TH man 1 "March 2014" "1.0" "git deploy man page"
.SH NAME
git deploy \- Deploy your codebase to the specified environment
.SH SYNOPSIS
git deploy <environment>
.SH DESCRIPTION
Finds the latest applicable tag in the repo and deploy it to its environment.
.SH OPTIONS
.TP
.I <environment>
Name of the environment to deploy to, the config for which is kept in .git-deploy
.I
.SH SEE ALSO
git-bump(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Barney Desmond <barneydesmond@gmail.com>
